Repository ErR0rpj/jain_songs, pull requests merged in 2024-04, with the labels that each got.

#88 Pachchhkhan
  lib/models/pachchhkhan_model.dart
  lib/screens/astronomy_screens/astronomy_bottom_sheet.dart
  lib/utilities/lists.dart
Labels: enhancement

#90 Pachchhkhan Complete
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  images/pray.png
  images/sunrise.png
  images/sunrise_white.png
  images/sunset.png
  images/sunset_white.png
  lib/custom_widgets/constant_widgets.dart
  lib/home_page.dart
  lib/main.dart
  lib/models/pachchhkhan_model.dart
  lib/screens/astronomy_screens/astronomy_bottom_sheet.dart
  lib/screens/post_screens/post_for_status.dart
  lib/services/database/database_controller.dart
  lib/services/database/firestore_helper.dart
  lib/services/network_helper.dart
  lib/services/services.dart
  lib/services/ui_settings.dart
  lib/services/useful_functions.dart
  lib/utilities/globals.dart
  lib/utilities/lists.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, update

#92 v2.2.0 - Pachchhkhan Introduced
  .gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  images/pray.png
  images/sunrise.png
  images/sunrise_white.png
  images/sunset.png
  images/sunset_white.png
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  lib/custom_widgets/constant_widgets.dart
  lib/home_page.dart
  lib/main.dart
  lib/models/pachchhkhan_model.dart
  lib/screens/astronomy_screens/astronomy_bottom_sheet.dart
  lib/screens/post_screens/post_for_status.dart
  lib/services/database/database_controller.dart
  lib/services/database/firestore_helper.dart
  lib/services/network_helper.dart
  lib/services/services.dart
  lib/services/ui_settings.dart
  lib/services/useful_functions.dart
  lib/settings_page.dart
  lib/utilities/globals.dart
  lib/utilities/lists.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, update, release

#99 pachhkhan categories, ui change, showcase shared preferences.
  android/app/src/main/AndroidManifest.xml
  lib/custom_widgets/constant_widgets.dart
  lib/home_page.dart
  lib/screens/astronomy_screens/astronomy_bottom_sheet.dart
  lib/services/database/database_controller.dart
  lib/services/database/firestore_helper.dart
  lib/services/database/realtime_db_helper.dart
  lib/services/network_helper.dart
  lib/services/shared_prefs.dart
  lib/utilities/globals.dart
  lib/utilities/lists.dart
  lib/utilities/song_details.dart
Labels: bug, enhancement, update

#101 changed status card in song page, changed icons of home and playlist,…
  lib/custom_widgets/constant_widgets.dart
  lib/home_page.dart
  lib/playlist_page.dart
  lib/screens/astronomy_screens/astronomy_bottom_sheet.dart
  lib/services/database/firestore_helper.dart
  lib/song_page.dart
  lib/utilities/globals.dart
  lib/utilities/lists.dart
Labels: bug, enhancement, update
